version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    env_file: 
      - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - "4000:80"
    volumes: 
       #Named volume
      - logs:/app/logs
       #Bind mount
      - ./backend:/app
       #Anonymous volume
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on: 
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: 
      - ./frontend/src:/app/src
    #Run in interactive mode
    stdin_open: true
    tty: true
    depends_on: 
        - backend

volumes: 
  data:
  logs: